// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPageFootball.Data;

#nullable disable

namespace RazorPageFootball.Migrations
{
    [DbContext(typeof(RazorPageFootballContext))]
    partial class RazorPageFootballContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("RazorPagesMovie.Models.CollegeFootball", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conference")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MasseyRating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalDefense")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalOffense")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CollegeFootball");
                });
#pragma warning restore 612, 618
        }
    }
}
